# Generated by Django 5.1.6 on 2025-03-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_dining_slug_listing_slug_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Prods/Accoms', 'verbose_name_plural': 'Prods/Accoms'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order [Prods/Accoms]', 'verbose_name_plural': 'orders [Prods/Accoms]'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Events/Blog', 'verbose_name_plural': 'Events/Blog'},
        ),
        migrations.RenameField(
            model_name='dining',
            old_name='active',
            new_name='in_use',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='in_use',
        ),
        migrations.AddField(
            model_name='dining',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('happening', 'Happening'), ('upcoming', 'Upcoming'), ('archived', 'Archived')], default='upcoming', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('user', 'User'), ('publisher', 'Publisher')], default='user', max_length=20, verbose_name='role'),
        ),
    ]
