# Generated by Django 5.1.6 on 2025-03-18 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_listing_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='dining/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('single', 'Single'), ('couple', 'Couple'), ('general', 'General')], max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('happening', 'Happening'), ('upcoming', 'Upcoming'), ('archived', 'Archived'), ('recent', 'Recent')], default='upcoming', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
