# Generated by Django 5.1.6 on 2025-11-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('marketplace', 'Marketplace'), ('accommodation', 'Accommodation'), ('dining', 'Dining')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
