# Generated by Django 5.1.6 on 2025-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Values',
        ),
        migrations.DeleteModel(
            name='Vission',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default=1, upload_to='team/'),
            preserve_default=False,
        ),
    ]
