# Generated by Django 5.1.6 on 2025-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_delete_mission_delete_values_delete_vission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
