# Generated by Django 5.1.6 on 2025-06-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_gallery_slider_testimonial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='action_text',
            field=models.CharField(blank=True, help_text='This is the text that will be displayed on the button [Make Impact, Join Us, Donate, etc.]. but make it short and concise', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='sliders/'),
        ),
    ]
