# Generated by Django 5.1.6 on 2025-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_slider_action_text_alter_slider_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-created_at'], 'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='action',
            field=models.CharField(blank=True, choices=[('join', 'Join'), ('donate', 'Donate'), ('none', 'None')], default='none', max_length=100, null=True),
        ),
    ]
