# Generated by Django 5.1.6 on 2025-06-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload slider image', null=True, upload_to='sliders/'),
        ),
    ]
