# Generated by Django 5.1.6 on 2025-06-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(help_text='This is the description of the video. make it short and concise'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='This is the url of the video. if it is youtube, make sure to use the embed url'),
        ),
    ]
