# Generated by Django 5.1.6 on 2025-10-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_video_description_alter_video_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('TikTok', 'TikTok'), ('Snapchat', 'Snapchat'), ('Reddit', 'Reddit')], default='Facebook', max_length=100),
        ),
        migrations.AlterField(
            model_name='teamsocialmedia',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('TikTok', 'TikTok'), ('Snapchat', 'Snapchat'), ('Reddit', 'Reddit')], default='Facebook', max_length=100),
        ),
    ]
